spring.application.name=backend

# Primary Database Configuration (Quota App)
spring.datasource.url=jdbc:postgresql://databasequotaapp.postgres.database.azure.com:5432/database.quota.app
spring.datasource.username=admindatabasequotaapp
spring.datasource.password=zNAj8TWuTh6:mfA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.jdbc-url=${spring.datasource.url}

# DMT Database Configuration
spring.datasource.dmt.url=jdbc:postgresql://dmt.postgres.database.azure.com:5432/database.dmt
spring.datasource.dmt.username=admindatabasedmt
spring.datasource.dmt.password=zNAj8TWuTh6:mfA
spring.datasource.dmt.driver-class-name=org.postgresql.Driver
spring.datasource.dmt.jdbc-url=${spring.datasource.dmt.url}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.implicit_naming_strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

# Server Configuration
server.port=8888

# JWT Configuration
jwt.secret=RyiCy94L77d'XlqcJ;-7Zd;$pdGC01PQ,!A,f;E9-}YkD(V^3U
jwt.expiration=86400000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pasindunaduninduwara@gmail.com
spring.mail.password=ujug tpve gqur jezw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Session Configuration
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.timeout=30m
spring.session.jdbc.table-name=SPRING_SESSION
spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-postgresql.sql
# Ensure Spring Session uses the primary DataSource
spring.session.jdbc.platform=postgresql

# Logging Configuration
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN
logging.level.com.quotaapp.backend=INFO